env:
  browser: true
  es2021: true
  jest/globals: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - airbnb
  - plugin:react/jsx-runtime
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - functional
  - import
  - jest
rules: {
  no-console: ['error', { allow: ['debug', 'warn', 'error'] }],
  semi: ['error', 'never'],
  no-unused-expressions: ['error', { 'allowTernary': true }],
  no-unsafe-optional-chaining: ['error', { 'disallowArithmeticOperators': false }],
  prefer-destructuring: ['error', {'object': true, 'array': false}],
  import/prefer-default-export:  ['off'],
  no-param-reassign: ['off'],
  import/no-cycle: [2, { maxDepth: 1 }],
  # react
  react/jsx-boolean-value: ['warn'],
  react/jsx-curly-brace-presence: ['warn'],
  react/jsx-fragments: ['warn'],
  react/jsx-no-useless-fragment: ['warn'],
  react/jsx-uses-react: ['off'],
  react/jsx-filename-extension: [1, { 'extensions': ['.js', '.jsx'] }],
  react/prefer-stateless-function: ['warn'],
  react/prop-types: ['off'],
  react/react-in-jsx-scope: ['off'],
  react/function-component-definition: [
    2,
    {
      namedComponents: 'arrow-function',
      unnamedComponents: 'arrow-function',
    },
  ],
  # functional
  functional/prefer-readonly-type: [
    'error',
    {
      allowLocalMutation: true,
      allowMutableReturnType: true,
      ignoreClass: true,
    },
  ],
  import/order: [
    'error',
    {
      groups: ['builtin', 'external', 'internal'],
      pathGroups: [
        {
          pattern: '{react,react-dom/**}',
          group: 'external',
          position: 'before',
        },
      ],
      pathGroupsExcludedImportTypes: ['react'],
      newlines-between: 'always',
      alphabetize: {
        order: 'asc',
        caseInsensitive: true,
      },
    },
  ],
  linebreak-style: ['error', 'unix'],
  eqeqeq: ['error', 'always', { null: 'ignore' }],
  camelcase: ['error', { properties: 'never' }],
  quotes: ['error', 'single', { avoidEscape: true }],
  # jest
  jest/no-disabled-tests: ['warn'],
  jest/no-focused-tests: ['error'],
  jest/no-identical-title: ['error'],
  jest/prefer-to-have-length: ['warn'],
  jest/valid-expect: ['error']
}
