env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - airbnb
  - plugin:react/jsx-runtime
overrides: [
    # {
    #   "files": [
    #     "/*.test.js",
    #   ]
    # }
]
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules: {
  react/jsx-filename-extension: [1, { "extensions": [".js", ".jsx"] }],
  semi: ["error", "never"],
  react/prop-types: ['off'],
  no-unused-expressions: ["error", { "allowTernary": true }],
  no-unsafe-optional-chaining: ["error", { "disallowArithmeticOperators": false }],
  prefer-destructuring: ["error", {"object": true, "array": false}],
  import/prefer-default-export:  ["off"],
  no-param-reassign: ["off"],
}
