export const USER_ACTION_TYPES = {
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  UPDATE_USER_TOKEN: 'UPDATE_USER_TOKEN',
  FETCH_CURRENT_USER_START: 'FETCH_CURRENT_USER_START',
  FETCH_CURRENT_USER_SUCCESS: 'FETCH_CURRENT_USER_SUCCESS',
  FETCH_CURRENT_USER_FAILURE: 'FETCH_CURRENT_USER_FAILURE',
  TOGGLE_DROPDOWN_VISIBLE: "TOGGLE_DROPDOWN_VISIBLE",
}